### ISSUE TITLE
Bug in Fully Connected Layer after recent update

### ISSUE THREAD

**Issue by Goobley** [VLL-HD/FrEIA#1]
Hi there,
After commit 379639ad1716b4a046873005f3f8c492f5b0bef3 there was a bug introduced in `coeff_functs.py`, line 96. It should read `out = self.fc2(out)`, but is instead  `out = self.fc2(x)`, leading to mismatched dimensions.

Cheers!

**Comment by tbung** [comment]
Good catch, thank you very much!
