### ISSUE TITLE
《Learning Likelihoods with Conditional Normalizing Flows code》 will release in next update?

### ISSUE THREAD

**Issue by Johnson-yue** [VLL-HD/FrEIA#11]

**Comment by ardizzone** [comment]
Hi!

We are familiar with the work, and think it would be a good Idea.
But at the moment, I can't promise it will be done any time soon.

The necessary functionality is already in the framework, only the actual method still has to be implemented.

If you happen to do it yourself, we will be happy to merge a pull request.

**Comment by Johnson-yue** [comment]
ok, I understand it ,  thanks for sharing ~~
