### ISSUE TITLE
Upload package to pypi

### ISSUE THREAD

**Issue by samet-akcay** [VLL-HD/FrEIA#114]
Hi, thanks a lot for open-sourcing this great library!

I was wondering if you could upload this package to pypi. Our [library](https://github.com/openvinotoolkit/anomalib) has `FrEIA` dependency now and we cannot update our pypi version since `FrEIA` is not on pypi. It would be great to have this library on pypi so the dependency conflicts could be easily resolved or the user could just do `pip install freia`.

Thanks again!

**Comment by psorrenson** [comment]
Hi, sorry for the late response to your request. FrEIA is now available on pip through `pip install FrEIA`. Thank you for the suggestion!
