### ISSUE TITLE
Why the log detminant of Reshape is 1?

### ISSUE THREAD

**Issue by XavierXiao** [VLL-HD/FrEIA#12]
Hi! Could you please look at the line indicated below? It is the log determinant of Reshape, which, as other reshaping methods, should be 0, but here it is 1. Correct me if I am wrong. Thanks!

https://github.com/VLL-HD/FrEIA/blob/b5d2a1ee363e8afd5c6b9435db5efa165e9ca9e4/FrEIA/modules/reshapes.py#L239

**Comment by ardizzone** [comment]
Yes, you are absolutely right. Thank you very much for pointing this out!

I have fixed it in dd51f4fa5897e017527c682a8c3508c29e507259
