### ISSUE TITLE
Clamping added later?

### ISSUE THREAD

**Issue by renatobellotti** [VLL-HD/FrEIA#19]
I have a question about the calmping in `RNVPCouplingBlock` and `GLOWCouplingBlock`.

Code from `RNVPCouplingBlock`:

```python
def e(self, s):
        # return torch.exp(torch.clamp(s, -self.clamp, self.clamp))
        # return (self.max_s-self.min_s) * torch.sigmoid(s) + self.min_s
        return torch.exp(self.clamp * 0.636 * torch.atan(s))
```

- The `atan()` call is not described in the paper. Has it been added later?
- Perhaps it would be a good idea to mention that 2 / pi ≃ 0.636 (actually, correctly rounded it's 0.637).

- Were the results from the `Analyzing Inverse problems with Invertible Neural Networks` paper obtained including the `atan`?

**Comment by ardizzone** [comment]
Hi!
Thanks for bringing this up.
Yes, indeed, the clamping was also present in the paper.
The clamping itself was already introduced by the Real-NVP paper, but you are right, it would have been good to include a detailed description of the coupling blocks, at least in the appendix of the paper.

I will close this issue and move it to the paper's own repository (this one now being only for FrEIA itself, which can implement various other bi-directional architectures and methods)
