### ISSUE TITLE
Experiments folder has disappeared

### ISSUE THREAD

**Issue by Johnson-yue** [VLL-HD/FrEIA#25]
when git clone this repo , the **Experiments** folder has disappeared

**Comment by ardizzone** [comment]
The experiments for each paper have been moved to separate repositories, the link to each is at the top of the README now:

https://github.com/VLL-HD/exact_information_bottleneck
https://github.com/VLL-HD/conditional_invertible_neural_networks
https://github.com/VLL-HD/analyzing_inverse_problems

We found this is a better system as we release more papers.
