### ISSUE TITLE
when using cINN ， input channel should be bigger than 1 ?

### ISSUE THREAD

**Issue by Johnson-yue** [VLL-HD/FrEIA#27]
Hi,  I want to try to train MNIST with convolution layers not fc_layers but I am failed.

mnist_minimal_example and mnist_cINN  both use fc layers. though input is (1, 28, 28)
but, Second Node both are Flatten to 784 feature

and colorization_*  input is (2, 64, 64)  

I test , if input is (1, X, X) will fail.  so , input channel should be bigger than 1 ? Would you plan to update this feature ?

**Comment by R41D3R** [comment]
I have the same Issue. @Johnson-yue Did you find a smooth workaround?

**Comment by Johnson-yue** [comment]
@R41D3R  My answer is yes it must be

**Comment by zuoshifan** [comment]
I have the same Issue. How do you solved it?

**Comment by zuoshifan** [comment]
I have the same Issue. @Johnson-yue  How do you solved it?

**Comment by zuoshifan** [comment]
I have the same Issue. @Johnson-yue How did you solve it?

**Comment by Johnson-yue** [comment]
@zuoshifan  I can not fix this bug
