### ISSUE TITLE
AttributeError: 'Visualizer' object has no attribute 'viz'

### ISSUE THREAD

**Issue by Johnson-yue** [VLL-HD/FrEIA#3]
Hi,  in experiments/mnist_cINN/viz.py this  there is not 'viz' in this file ..

**Comment by ardizzone** [comment]
It should be fixed (537287b).
Could you check, and if not, paste the whole error message?

Note: it should not have affected training, you can just use the _ABORT checkpoint that was created when the error happened.

**Comment by Johnson-yue** [comment]
Yes, I train successfully, and I got a  model, but I had not do more experiments like Fig7 , I will try it out.

**Comment by Johnson-yue** [comment]
@ardizzone Hi， you said add noise to input image is better performance， I think there is a paper called [On Stabilizing Generative Adversarial Training with Noise ](https://github.com/sjenni/dfgan) can explain  why the noise is importance, and maybe it help your framework is better .

**Comment by ardizzone** [comment]
Very interesting, thank you for pointing this paper out!
