### ISSUE TITLE
Guidance on network sizes

### ISSUE THREAD

**Issue by extragoya** [VLL-HD/FrEIA#37]
Excellent library! I'm wondering if there are any tips/guidance from the community on how to choose the network architecture and depth. Currently I'm trying to do unconditional generation of ultrasound images (downsampled to 64x64), but I don't know where to start in terms of how big of an INN network to use (e.g., should I aim for ~30 coupling layers or ~300 layers). 

The images used here: https://github.com/VLL-HD/conditional_invertible_neural_networks are maybe a simpler distribution, so I'm not how relevant the model architectures are for my task.

Just don't have the working experience that comes with standard NNs to at least get a starting point. Does anyone else have any experience they'd like to share so I can bootstrap off of them? E.g., strategies that work toward getting to a INN architecture that's appropriate?

**Comment by extragoya** [comment]
Thanks Paul, I appreciate your response. I am actually pretty familiar with training standard deep NNs and the best practices therein, so I was mainly wondering if there are any considerations specific to INNs, particularly given how one has to choose the latent size and other aspects that are unique to these architectures. As for your list, it is a good outline of some nice principles for training NNs, which I also follow in my own work. Thanks again.

**Comment by ardizzone** [comment]
Hi!
I will close this issue, as psteinb has given a quite complete answer, but feel free to reach out if you have more questions!
We are working on a more comprehensive tutorial this week an next, to hopefully offer some better guidance in future.
