### ISSUE TITLE
when you train colorization_cINN with lsun_bedroom , how many pictures you used?

### ISSUE THREAD

**Issue by Johnson-yue** [VLL-HD/FrEIA#4]
I download the LSUN bedroom dataset , the lmdb format is 54G, when I export it to image flie like png, It very huge maybe 500G , so do you use all Lsun bedroom images to train this model??

**Comment by ardizzone** [comment]
Hi,

I apologize for the late answer, I was traveling the past weeks.
We used the 128Px version of the dataset. The authors of the "Improved WGAN training" paper provide this link:
https://s3.amazonaws.com/ishaan-misc/lsun_128_train.tar.gz

The archive contains all 3M images, but at a lower resolution.

**Comment by Johnson-yue** [comment]
Ok， I will try it， the 128 is enough for me，thank you and have a nice day
