### ISSUE TITLE
Tests failed

### ISSUE THREAD

**Issue by aarontuor** [VLL-HD/FrEIA#45]
test_jacobian fails with pytorch=1.6.0=py3.7_cuda9.2.148_cudnn7.6.3_0

======================================================================
FAIL: test_jacobian (__main__.ConditioningTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "conditioning.py", line 92, in test_jacobian
    self.assertTrue(torch.allclose(logdet, logdet_num, atol=0.1, rtol=0.1))
AssertionError: False is not true

======================================================================
FAIL: test_jacobian (__main__.IResNetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "invertible_resnet.py", line 149, in test_jacobian
    self.assertTrue(torch.allclose(logdet, logdet_num, atol=1.5, rtol=0.1))
AssertionError: False is not true

Any ideas here?

**Comment by ardizzone** [comment]
Should be fixed by e76808ca3a65036c00fd3e1ff0a3161e59e8a2af
