### ISSUE TITLE
Prescription for subnet constructor using classes:

### ISSUE THREAD

**Issue by DebajyotiS** [VLL-HD/FrEIA#48]
Hello all,

I am trying to write a class for the neural nets in the coupling blocks. For instance:
```

class subnetDense(nn.Module):

    def __init__(self, input_dim, output_dim, hidden_dim):
        super().__init__()
        self.input_dim = input_dim
        self.output_dim = output_dim
        self.hidden_dim = hidden_dim
        current_dim = input_dim
        self.layers = nn.ModuleList()
        for hdim in hidden_dim:
            self.layers.append(nn.Linear(current_dim, hdim))
            current_dim = hdim
        self.layers.append(nn.Linear(current_dim, output_dim))

    def forward(self, x):
        for layer in self.layers[:-1]:
            x = F.relu(layer(x))
        out = F.softmax(self.layers[-1](x))
        return out

layerlist = [128,128,128]   

nodes = [Ff.InputNode(2, name='input')]
for k in range(3):
    nodes.append(Ff.Node(nodes[-1],
                         Fm.GLOWCouplingBlock,
                         {'subnet_constructor':subnetDense(2,2,layerlist), 'clamp':2.0},
                         name=F'coupling_{k}'))

nodes.append(Ff.OutputNode(nodes[-1], name='output'))
inn = Ff.ReversibleGraphNet(nodes)
```

However, this gives me an error :
 `forward() takes 2 positional arguments but 3 were given`.

I note that creating the subnet with nn.sequential works, but can I do it with classes? I am assuming I am somehow required to output a torch nn.module. I essentially want to have the number of hidden layers passed in as a parameter and there is no pretty way of doing it with nn.sequential. 

Edit: 
I now see that the source of error is that the coupling modules defined in the package require a subnet constructor with the signature (input_dim, output_dim) - this then means when my class is being invoked it is looking at the forward function - which only takes in x. 

Regards,
Debajyoti

**Comment by DebajyotiS** [comment]
Found a solution to the issue - OrderedDict. 
All these years with Keras has made me lazy! 😜

**Comment by psteinb** [comment]
Just out of curiosity: Where did you use the `OrderedDict`?

**Comment by DebajyotiS** [comment]
Hey,

I use orderedDict with nn.Sequential:
```

class subnetDense(nn.Module):
    def __init__(self, input_dim, output_dim, depth, ibw_width):
        super().__init__()
        self.depth = depth
        self.ibw = ibw_width
        self.input_dim = input_dim
        self.output_dim = output_dim

    def forward(self, input_dim, output_dim):
        td = OrderedDict()
        td['lin1'] = nn.Linear(self.input_dim, self.ibw)
        td['rel1'] = nn.ReLU()
        for i in range(2, self.depth-1):
            td[f'lin{i}'] = nn.Linear(self.ibw, self.ibw)
            td[f'rel{i}'] = nn.ReLU()
        td[f'lin{self.depth}'] = nn.Linear(self.ibw, self.output_dim)
        td[f'rel{self.depth}'] = nn.ReLU()
        mod = nn.Sequential(td)
        return mod
```

**Comment by psteinb** [comment]
Interesting, Thanks for sharing. 

I am confused to see `nn.Sequential` in the `forward` method above. To my knowledge, `forward` is called for every forward pass of the model - so tons of times during training. That said, constructing `Sequential` within `forward` might incur an unnecessary overhead.

To be fair, the API docs are not very clear on this [1].
And the docs of the `forward` function of `nn.Module` from which `nn.Sequential` inherits [2].

Based on examples like this [3] and this blog [4], I typically instantiate `nn.Sequential` in the constructor of the network class I am using, i.e. inside `subnetDense.__init__` in your case.

[1]: https://pytorch.org/docs/stable/generated/torch.nn.Sequential.html#torch.nn.Sequential
[2]: https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.forward
[3]: https://github.com/pytorch/examples/blob/792d336019a28a679e29cf174e10cee80ead8722/snli/model.py#L52
[4]: https://towardsdatascience.com/pytorch-how-and-when-to-use-module-sequential-modulelist-and-moduledict-7a54597b5f17

**Comment by DebajyotiS** [comment]
I think I reverted to this because for the subnet constructor - I require a method with the signature f(input_dim, output_dim) that returns a torch module. I could write a simple function getSubnetDense(in, out) with the nn.Sequential and orderedDict that returns a torch module, but I am not sure how to do that with a class - thus, as you rightly pointed out, my clunky forward method. 
Perhaps there's a trick I am missing?

**Comment by ardizzone** [comment]
Hi! Your solution is the right way to do it in principle, albeit a little confusing! :D
Towards what psteinb says, what you call the 'subnetDense' is only called once, when the coupling block is constructed.
So it doesn't have to be a subclass of nn.Module or anything.
What you have really done here, is write a factory class.
How I would usually do that is the following, I'm sure you can adapt your code to make it simpler:

```python
class SubnetConstructor:
    def __init__(self, ch_hidden, kaiming_gain):
        self.ch_hidden = ch_hidden
        self.kaiming_gain = kaiming_gain
        
    def __call__(self, ch_in, ch_out):
        # whaver subnet you want to make:
        net = nn.Sequetial(nn.Linear(ch_in, self.ch_hidden),
                                   nn.ReLu(),
                                   nn.Linear(self.ch_hidden, ch_out)) 
       
        # whatever initialization you want to apply:
        net.apply(lambda m: nn.init.kaiming_uniform_(m, gain=self.kaiming_gain))
        return net

subet_constr = SubnetConstructor(ch_hidden=64, kaiming_gain=0.7)
nodes = [Ff.InputNode(2, name='input')]
for k in range(3):
    nodes.append(Ff.Node(nodes[-1],
                         Fm.GLOWCouplingBlock,
                         {'subnet_constructor':subnet_constr, 'clamp':2.0},
                         name=F'coupling_{k}'))
# etc.
```

We will try to add this to the new tutorial we are working on.
