### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by samyak0210** [VLL-HD/FrEIA#7]
Can a pretrained model trained on ImageNet  be released as well?

**Comment by ardizzone** [comment]
Certainly, here is the checkpoint that was used for all experiments:
https://drive.google.com/open?id=1gpHHtT7EcCoEqTzaUmDImp_tyB7vSKIN

It should work out of the box with the evaluation script.
Could you let me know if it works as expected for you? Then I can close the issue and update the readme with the link.

Best regards
Lynton Ardizzone

**Comment by samyak0210** [comment]
@ardizzone Is this the model trained on the ImageNet dataset?

**Comment by ardizzone** [comment]
Yes, ImageNet at 256x256 pixels (as opposed to the usual 224x224).
Let me know if you need further details.

**Comment by samyak0210** [comment]
Hey @ardizzone , which file should I look into for checking whether this model works or not?

**Comment by ardizzone** [comment]
I checked myself that the checkpoint is correctly loaded, thank you for your patience.

I just made commit b5d2a1ee363e8afd5c6b9435db5efa165e9ca9e4
that contains a readme file with the links.

Please, don't hesitate to let me know if there are any further problems!
