### ISSUE TITLE
How to cite this repo?

### ISSUE THREAD

**Issue by ThyrixYang** [VLL-HD/FrEIA#94]
Hi, 

I used the freia lib in my work, and I want to cite it in my paper, could you provide a proper bibtex entry?

**Comment by BIGBALLON** [comment]
The same issue for me

**Comment by kunwuz** [comment]
Thanks for the awesome library, any update about this question would be appreciated.

**Comment by psorrenson** [comment]
Hi, sorry for the late response to your request. We now include information about how to cite FrEIA in the readme. Thanks!
